channels:
- conda-forge
dependencies:
- python >=3.11,<3.14
- hatchling =1.27.0
- hatch-vcs =0.5.0
- hatch-jupyter-builder >=0.5.0
- papermill
- anywidget =0.9.18
- black =25.1.0
- cloudpickle =3.1.1
- ipytree =0.2.2
- ipywidgets =8.1.6
- jupyterlab =4.4.1
- numpy =1.26.4
- sqlalchemy =2.0.38
- traitlets =5.14.3
- ase =3.24.0
- assyst =0.3.0
- bayesian-optimization =2.0.3
- calphy =1.3.13
- grace-tensorpotential =0.5.1
- iprpy-data =2023.07.25
- lammps =2024.08.29=*openmpi*
- landau =1.3.4
- matgl =1.1.3
- matplotlib =3.10.0
- nglview =3.1.4
- pandas =2.2.3
- phonopy =2.43.2
- pint =0.24.4
- psycopg2 =2.9.9
- pyiron_atomistics =0.7.18
- pyiron_base =0.14.3
- pyiron-data =0.0.30
- pyiron_lammps =0.4.1
- python-ace =0.3.1
- python-ternary =1.0.8
- pyxtal =1.1.0
- scikit-image =0.25.2
- scikit-learn =1.6.1
- scipy =1.15.2
- seaborn =0.13.2
- structuretoolkit = 0.0.32
- nodejs=18
- postgresql
