name: Test suite
on: [pull_request]

jobs:
  test-suite:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Build environment from file
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
          miniforge-version: latest
          channels: conda-forge
          conda-remove-defaults: true
          channel-priority: strict
          environment-file: project-env.yml
        timeout-minutes: 5

      - name: Build package
        shell: bash -l {0}
        run: |
          pip install . --no-deps --no-build-isolation
        timeout-minutes: 1

      - name: Execute notebooks
        shell: bash -l {0}
        run: |
          failed_notebooks=()
    
          for notebook in ./notebooks/liam/*.ipynb; do
            echo "Executing: $notebook"
            if papermill "$notebook" "$notebook"; then
              echo "✓ PASSED: $notebook"
            else
              echo "✗ FAILED: $notebook" 
              failed_notebooks+=("$notebook")
            fi
          done
          
          if [ ${#failed_notebooks[@]} -ne 0 ]; then
            echo "Failed notebooks: ${failed_notebooks[*]}"
            exit 1
          fi
          echo "All notebooks passed!"
        timeout-minutes: 5
